make it clear that pinning is possible on other endpoints than files
ethersphere/docs.github.io pull request #111
Opened 2021-01-07 09:48 UTC by Eknir

2021-01-07 14:16 UTC, attila-lendvai requested changes

2021-01-07 14:16 UTC, attila-lendvai commented on docs/advanced/persistence.md
> +Pinning and unpinning is possible file (as in the example), chunks, directories and bytes
```suggestion
Pinning and unpinning is possible for files (as in the example), chunks, directories, and bytes
```

2021-01-07 16:45 UTC, attila-lendvai commented on docs/advanced/persistence.md
> +Pinning and unpinning is possible file (as in the example), chunks, directories and bytes
@Eknir FYI, you can apply these suggestions right here on the github web UI

2021-01-07 21:19 UTC, attila-lendvai approved these changes

2021-01-07 21:21 UTC, attila-lendvai commented on docs/advanced/persistence.md
> +Pinning and unpinning is possible for files (as in the example), chunks, directories, and bytes
i'm not exactly sure what "bytes" is, but i also haven't read the docs, so... :) i have an idea, but don't take my approval in the review as a well-informed one.

2021-01-09 09:51 UTC, significance approved these changes

2021-01-20 12:41 UTC, merged