add warn box, explaining that not all valid tars are valid paths for …
ethersphere/docs.github.io pull request #112
Opened 2021-01-07 10:32 UTC by Eknir

…http routers

2021-01-12 09:11 UTC, attila-lendvai requested changes

2021-01-12 09:11 UTC, attila-lendvai commented on docs/getting-started/upload-a-directory.md
> +Not all directory structures, as supported by tar, can be supported in Bee. The differences arises, as not all valid directory structures are valid paths for an HTTP router (e.g. paths which are in a
- broke lines for better diff experience in the future
- which -> that
- accesible -> accessible

```suggestion
Not all directory structures, as supported by tar, can be supported in Bee.
The differences arises, as not all valid directory structures are valid paths
for an HTTP router (e.g. paths that are in a parent directory to the root).
Bee will accept and upload the invalid directory structures, but some of
your content might not be accessible.
```

2021-01-20 12:42 UTC, Eknir commented
@attila-lendvai , can you review again please?

2021-01-20 12:58 UTC, significance approved these changes

2021-01-20 22:09 UTC, attila-lendvai approved these changes

2021-01-24 14:51 UTC, merged