added info and warn box with respect to resolver configuration
ethersphere/docs.github.io pull request #114
Opened 2021-01-07 13:51 UTC by Eknir

2021-01-12 09:19 UTC, attila-lendvai requested changes

2021-01-12 09:19 UTC, attila-lendvai commented on docs/getting-started/host-your-website-using-ENS.md
> +Use the `resolver-options` flag to set point the bee resolver to any ens-compatible smart-contract on any evm-compatible chain
```suggestion
Use the `resolver-options` flag to point the bee resolver to any ENS compatible smart-contract on any EVM compatible chain
```

2021-01-12 09:19 UTC, attila-lendvai commented on docs/getting-started/host-your-website-using-ENS.md
> +When your bee node, or the bee node of a gateway that you are interacting with is not connected to the standard EVM contract on Ethereum mainnet, familiar names (e.g. `swarm.eth`) may resolve to diff
```suggestion
When your bee node, or the bee node of a gateway that you are interacting with, is not connected to the standard EVM contract on Ethereum mainnet, then familiar names (e.g. `swarm.eth`) may resolve to different content.
```

2021-01-20 12:51 UTC, Eknir commented
@attila-lendvai , Thanks for the proposals! Could you please have a look again?

2021-01-20 12:55 UTC, significance approved these changes

2021-01-20 12:55 UTC, significance commented on docs/getting-started/host-your-website-using-ENS.md
> +When your bee node, or the bee node of a gateway that you are interacting with, is not connected to the standard EVM contract on Ethereum mainnet, then familiar names (e.g. `swarm.eth`) may resolve t
```suggestion
Make sure you trust the gateway you are interacting with. To be sure you are retrieving the correct content run your own ENS resolver and Bee node. 
```

2021-01-20 22:11 UTC, attila-lendvai requested changes

2021-01-20 22:11 UTC, attila-lendvai commented on docs/getting-started/host-your-website-using-ENS.md
> +Make sure you trust the gateway you are interacting with. To be sure you are retrieving the correct content run your own ENS resolver and Bee node.
```suggestion
Make sure you trust the gateway you are interacting with! To ensure that you are retrieving the correct content, run your own ENS resolver and Bee node.
```

2021-01-20 22:13 UTC, attila-lendvai commented
@Eknir AFAIK, you can accept these "request changes" suggestions that i'm creating with a single click, right here on github. let me know if your workflow includes more hassle than that!

2021-01-24 15:06 UTC, attila-lendvai approved these changes

2021-01-24 16:05 UTC, merged