Beta
ethersphere/docs.github.io pull request #81
Opened 2020-09-26 18:24 UTC by significance

Updates and makes additions to the Bee documentation. Should correspond to the Beta release.

2020-09-26 19:17 UTC, zelig requested changes

2020-09-26 19:17 UTC, zelig commented on docs/experimental/pss.md
> +When sending messages, we must specify the first two bytes of the recipients swarm address, which represents their neighbourhood. In this case, we want to send to a node with address `49d80b28adccd67
well, whether it is 2 bytes or not depends  on the network size. maybe ok  not to overcomplicate,  but   maybe:

a prefix of the recipients swarm address,  a partial  address reptesenting their neighbourhood.  Currently  the  length of this prefix is  recommended  to be two bytes  which will  work until a network size of upto ca.  20-50K nodes

2020-09-26 19:17 UTC, zelig commented on docs/experimental/pss.md
> +:::danger
remove

2020-09-26 19:17 UTC, zelig commented on docs/experimental/pss.md
> +curl -XPOST localhost:8082/pss/send/test/49d8 --data "test2"
specify recipient public key in query param `recipient`.  Format is hex-encoded public key  in compressed or uncompressed format

2020-09-27 08:23 UTC, significance commented on docs/experimental/pss.md
> +PSS is currently an experimental feature and messages are not currently encrypted! Encryption is coming soon, but for now this feature should be used for evaluation and non-sensitive purposes only. A
sweet

2020-09-27 08:35 UTC, ralph-pichler commented on docs/experimental/swap.md
> +To enable SWAP mode, you must include configuration paramaters `--swap-enabled`, and also a valid [Goerli Testnet](https://goerli.net/) RPC endpoint. An example of this is provided at [rpc.slock.it/g
Maybe move the own node part to the front. This is really the mode that should be encouraged, especially for goerli where this is very feasable (fast sync can be completed in <1h).

2020-09-27 08:35 UTC, ralph-pichler commented on docs/experimental/swap.md
> +INFO[2020-09-26T14:52:23+01:00] deploying new chequebook
heads up that the output might change here a bit.

2020-09-27 08:35 UTC, ralph-pichler commented on docs/installation/configuration.md
> +#### --clef-signer-endpoint
should be added somewhere that using clef only makes sense with a fitting rules files or if running in `--advanced` to allow for auto-signing of handshakes and cheques.

2020-09-28 11:42 UTC, ralph-pichler commented on docs/experimental/swap.md
> +To enable SWAP mode, you must include configuration paramaters `--swap-enabled`, and also a valid [Goerli Testnet](https://goerli.net/) RPC endpoint. You can run your [own Goerli node](https://github
Swap enabled by default, flag no longer necessary.

2020-09-28 11:42 UTC, ralph-pichler commented on docs/experimental/swap.md
> +	--swap-enable \
remove

2020-09-28 11:42 UTC, ralph-pichler commented on docs/experimental/swap.md
> +Error: insufficient token for initial deposit
message looks a bit different now.

2020-09-28 11:42 UTC, ralph-pichler commented on docs/experimental/swap.md
> +INFO[2020-09-26T14:52:23+01:00] deploying new chequebook
has actually changed to include more info

2020-09-28 11:42 UTC, ralph-pichler commented on docs/experimental/swap.md
> +
We should at least add something about `/chequebook/cheque`/`/chequebook/cheque/<peer>`. 

`/chequebook/deposit` and `/chequebook/withdraw` could also be added but are not as important.

2020-09-28 11:42 UTC, ralph-pichler commented on docs/installation/configuration.md
> +#### --swap-enable                    enable swap
should maybe be changed now that it's default

2020-09-28 12:27 UTC, ralph-pichler commented on docs/experimental/swap.md
> +	--swap-endpoint https://rpc.slock.it/goerli \
`--swap-initial-deposit` is missing. should be `100000000` if faucet is used.

2020-09-28 14:42 UTC, ralph-pichler commented on docs/advanced/pss.md
> +bee start \
If you're running a local two node network you should probably run with `--swap-enable=false`

2020-09-28 14:52 UTC, acud approved these changes

2020-09-28 14:56 UTC, merged